/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as ManutencaoRouteImport } from './routes/manutencao'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'
import { Route as ClientesNovoRouteImport } from './routes/clientes.novo'
import { Route as LocacoesIndexRouteImport } from './routes/locacoes.index'
import { Route as LocacoesIdRouteImport } from './routes/locacoes.$id'
import { Route as LocacoesNovoRouteImport } from './routes/locacoes.novo'
import { Route as LocacoesTranslatoRouteImport } from './routes/locacoes.translato'
import { Route as LogsIndexRouteImport } from './routes/logs.index'
import { Route as LogsIdRouteImport } from './routes/logs.$id'
import { Route as VeiculosIndexRouteImport } from './routes/veiculos.index'
import { Route as VeiculosIdRouteImport } from './routes/veiculos.$id'
import { Route as VeiculosNovoRouteImport } from './routes/veiculos.novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ManutencaoRoute = ManutencaoRouteImport.update({
  id: '/manutencao',
  path: '/manutencao',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesNovoRoute = ClientesNovoRouteImport.update({
  id: '/clientes/novo',
  path: '/clientes/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const LocacoesIndexRoute = LocacoesIndexRouteImport.update({
  id: '/locacoes/',
  path: '/locacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocacoesIdRoute = LocacoesIdRouteImport.update({
  id: '/locacoes/$id',
  path: '/locacoes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LocacoesNovoRoute = LocacoesNovoRouteImport.update({
  id: '/locacoes/novo',
  path: '/locacoes/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const LocacoesTranslatoRoute = LocacoesTranslatoRouteImport.update({
  id: '/locacoes/translato',
  path: '/locacoes/translato',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIndexRoute = LogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIdRoute = LogsIdRouteImport.update({
  id: '/logs/$id',
  path: '/logs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VeiculosIndexRoute = VeiculosIndexRouteImport.update({
  id: '/veiculos/',
  path: '/veiculos/',
  getParentRoute: () => rootRouteImport,
} as any)
const VeiculosIdRoute = VeiculosIdRouteImport.update({
  id: '/veiculos/$id',
  path: '/veiculos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VeiculosNovoRoute = VeiculosNovoRouteImport.update({
  id: '/veiculos/novo',
  path: '/veiculos/novo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/documentos': typeof DocumentosRoute
  '/financeiro': typeof FinanceiroRoute
  '/manutencao': typeof ManutencaoRoute
  '/usuarios': typeof UsuariosRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/clientes/novo': typeof ClientesNovoRoute
  '/locacoes/$id': typeof LocacoesIdRoute
  '/locacoes/novo': typeof LocacoesNovoRoute
  '/locacoes/translato': typeof LocacoesTranslatoRoute
  '/logs/$id': typeof LogsIdRoute
  '/veiculos/$id': typeof VeiculosIdRoute
  '/veiculos/novo': typeof VeiculosNovoRoute
  '/clientes/': typeof ClientesIndexRoute
  '/locacoes/': typeof LocacoesIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/veiculos/': typeof VeiculosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/documentos': typeof DocumentosRoute
  '/financeiro': typeof FinanceiroRoute
  '/manutencao': typeof ManutencaoRoute
  '/usuarios': typeof UsuariosRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/clientes/novo': typeof ClientesNovoRoute
  '/locacoes/$id': typeof LocacoesIdRoute
  '/locacoes/novo': typeof LocacoesNovoRoute
  '/locacoes/translato': typeof LocacoesTranslatoRoute
  '/logs/$id': typeof LogsIdRoute
  '/veiculos/$id': typeof VeiculosIdRoute
  '/veiculos/novo': typeof VeiculosNovoRoute
  '/clientes': typeof ClientesIndexRoute
  '/locacoes': typeof LocacoesIndexRoute
  '/logs': typeof LogsIndexRoute
  '/veiculos': typeof VeiculosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/documentos': typeof DocumentosRoute
  '/financeiro': typeof FinanceiroRoute
  '/manutencao': typeof ManutencaoRoute
  '/usuarios': typeof UsuariosRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/clientes/novo': typeof ClientesNovoRoute
  '/locacoes/$id': typeof LocacoesIdRoute
  '/locacoes/novo': typeof LocacoesNovoRoute
  '/locacoes/translato': typeof LocacoesTranslatoRoute
  '/logs/$id': typeof LogsIdRoute
  '/veiculos/$id': typeof VeiculosIdRoute
  '/veiculos/novo': typeof VeiculosNovoRoute
  '/clientes/': typeof ClientesIndexRoute
  '/locacoes/': typeof LocacoesIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/veiculos/': typeof VeiculosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/documentos'
    | '/financeiro'
    | '/manutencao'
    | '/usuarios'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/locacoes/$id'
    | '/locacoes/novo'
    | '/locacoes/translato'
    | '/logs/$id'
    | '/veiculos/$id'
    | '/veiculos/novo'
    | '/clientes/'
    | '/locacoes/'
    | '/logs/'
    | '/veiculos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/documentos'
    | '/financeiro'
    | '/manutencao'
    | '/usuarios'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/locacoes/$id'
    | '/locacoes/novo'
    | '/locacoes/translato'
    | '/logs/$id'
    | '/veiculos/$id'
    | '/veiculos/novo'
    | '/clientes'
    | '/locacoes'
    | '/logs'
    | '/veiculos'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/documentos'
    | '/financeiro'
    | '/manutencao'
    | '/usuarios'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/locacoes/$id'
    | '/locacoes/novo'
    | '/locacoes/translato'
    | '/logs/$id'
    | '/veiculos/$id'
    | '/veiculos/novo'
    | '/clientes/'
    | '/locacoes/'
    | '/logs/'
    | '/veiculos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DocumentosRoute: typeof DocumentosRoute
  FinanceiroRoute: typeof FinanceiroRoute
  ManutencaoRoute: typeof ManutencaoRoute
  UsuariosRoute: typeof UsuariosRoute
  ClientesIdRoute: typeof ClientesIdRoute
  ClientesNovoRoute: typeof ClientesNovoRoute
  LocacoesIdRoute: typeof LocacoesIdRoute
  LocacoesNovoRoute: typeof LocacoesNovoRoute
  LocacoesTranslatoRoute: typeof LocacoesTranslatoRoute
  LogsIdRoute: typeof LogsIdRoute
  VeiculosIdRoute: typeof VeiculosIdRoute
  VeiculosNovoRoute: typeof VeiculosNovoRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  LocacoesIndexRoute: typeof LocacoesIndexRoute
  LogsIndexRoute: typeof LogsIndexRoute
  VeiculosIndexRoute: typeof VeiculosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencao': {
      id: '/manutencao'
      path: '/manutencao'
      fullPath: '/manutencao'
      preLoaderRoute: typeof ManutencaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/novo': {
      id: '/clientes/novo'
      path: '/clientes/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof ClientesNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locacoes/': {
      id: '/locacoes/'
      path: '/locacoes'
      fullPath: '/locacoes/'
      preLoaderRoute: typeof LocacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locacoes/$id': {
      id: '/locacoes/$id'
      path: '/locacoes/$id'
      fullPath: '/locacoes/$id'
      preLoaderRoute: typeof LocacoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locacoes/novo': {
      id: '/locacoes/novo'
      path: '/locacoes/novo'
      fullPath: '/locacoes/novo'
      preLoaderRoute: typeof LocacoesNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locacoes/translato': {
      id: '/locacoes/translato'
      path: '/locacoes/translato'
      fullPath: '/locacoes/translato'
      preLoaderRoute: typeof LocacoesTranslatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/': {
      id: '/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof LogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/$id': {
      id: '/logs/$id'
      path: '/logs/$id'
      fullPath: '/logs/$id'
      preLoaderRoute: typeof LogsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veiculos/': {
      id: '/veiculos/'
      path: '/veiculos'
      fullPath: '/veiculos/'
      preLoaderRoute: typeof VeiculosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veiculos/$id': {
      id: '/veiculos/$id'
      path: '/veiculos/$id'
      fullPath: '/veiculos/$id'
      preLoaderRoute: typeof VeiculosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veiculos/novo': {
      id: '/veiculos/novo'
      path: '/veiculos/novo'
      fullPath: '/veiculos/novo'
      preLoaderRoute: typeof VeiculosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DocumentosRoute: DocumentosRoute,
  FinanceiroRoute: FinanceiroRoute,
  ManutencaoRoute: ManutencaoRoute,
  UsuariosRoute: UsuariosRoute,
  ClientesIdRoute: ClientesIdRoute,
  ClientesNovoRoute: ClientesNovoRoute,
  LocacoesIdRoute: LocacoesIdRoute,
  LocacoesNovoRoute: LocacoesNovoRoute,
  LocacoesTranslatoRoute: LocacoesTranslatoRoute,
  LogsIdRoute: LogsIdRoute,
  VeiculosIdRoute: VeiculosIdRoute,
  VeiculosNovoRoute: VeiculosNovoRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  LocacoesIndexRoute: LocacoesIndexRoute,
  LogsIndexRoute: LogsIndexRoute,
  VeiculosIndexRoute: VeiculosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
